version: 2

updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      main:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      main:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
