# Install dependencies and build app
FROM node:24-alpine AS build
WORKDIR /app
COPY . /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG NEXT_PUBLIC_CLOUDFLARE_CHALLENGE_SITE_KEY
ENV NEXT_PUBLIC_CLOUDFLARE_CHALLENGE_SITE_KEY=$NEXT_PUBLIC_CLOUDFLARE_CHALLENGE_SITE_KEY
ARG SENTRY_AUTH_TOKEN
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ENV SENTRY_ORG=$SENTRY_ORG
ARG SENTRY_PROJECT
ENV SENTRY_PROJECT=$SENTRY_PROJECT
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN
RUN npm ci && npm run build

# Clean app
FROM build
RUN rm -rf src/ vitest.config.mts next-env.d.ts package-lock.json testEnvironment.ts tsconfig.json
RUN npm prune --omit=dev

EXPOSE 3000
CMD ["npm", "start"]
