name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  test-app:
    runs-on: ubuntu-latest

    name: Test app

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test linting
        run: npm run test:linting

      - name: Test types
        run: npm run test:types

      - name: Test jest
        run: npm run test:jest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-terraform:
    runs-on: ubuntu-latest

    name: Test Terraform

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.10.5

      - name: Test formatting
        run: terraform fmt -list=true -check -recursive -diff
