name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    name: Test app

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test eslint
        run: npm run test:eslint

      - name: Test stylelint
        run: npm run test:stylelint

      - name: Test TypeScript
        run: npm run test:typescript

      - name: Test unit
        run: npm run test:unit

  test-terraform:
    runs-on: ubuntu-latest

    name: Test Terraform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3

      - name: Test formatting
        run: terraform fmt -list=true -check -recursive -diff

      - name: Analyze IAC
        uses: advanced-security/codeql-extractor-iac@v0.4.1
